
version: '3.8'
services:
  simple-app:
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "8082:8080"
    container_name: simple-app-compose-container

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080" # Expose Jenkins on port 8081
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins_server

volumes:
  jenkins_home: